-- 0003_programa_vip.sql
-- Copiado literal de index.js (bloque "Programa VIP por niveles").

ALTER TABLE customers ADD COLUMN IF NOT EXISTS nivel_vip INTEGER DEFAULT 0;

ALTER TABLE rates
    ADD COLUMN IF NOT EXISTS umbral_vip_1 NUMERIC DEFAULT 10000,
    ADD COLUMN IF NOT EXISTS umbral_vip_2 NUMERIC DEFAULT 25000,
    ADD COLUMN IF NOT EXISTS umbral_vip_3 NUMERIC DEFAULT 50000,
    ADD COLUMN IF NOT EXISTS bono_vip_1 NUMERIC DEFAULT 1,
    ADD COLUMN IF NOT EXISTS bono_vip_2 NUMERIC DEFAULT 2,
    ADD COLUMN IF NOT EXISTS bono_vip_3 NUMERIC DEFAULT 3,
    ADD COLUMN IF NOT EXISTS descuento_entrega_1 NUMERIC DEFAULT 50,
    ADD COLUMN IF NOT EXISTS descuento_entrega_2 NUMERIC DEFAULT 75,
    ADD COLUMN IF NOT EXISTS descuento_entrega_3 NUMERIC DEFAULT 100;

ALTER TABLE ofertas
    ADD COLUMN IF NOT EXISTS texto_vip TEXT,
    ADD COLUMN IF NOT EXISTS activa_vip BOOLEAN DEFAULT false;
